command_center/urls.py
from django.urls import path

from . import views

app_name = 'command_center'
urlpatterns = [
    path('', views.MainMenu.as_view(), name='main_menu'),
    path('command/', views.MainMenu.as_view(), name='main_menu'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/<pk>', views.ProjectDetailView.as_view(), name='project_detail'),    # This is called for projects that do not have their own app
    path('robot_list/', views.RobotListView.as_view(), name='robot_list'),
    # path('robot_list/<model>', views.RobotListView.as_view(), name='robot_list_view'),
    # # path('robot_details/<pk>', views.RobotDetailsView.as_view(), name='robot_details_view'),
    # path('robot_details/<pk>', views.RobotDetailsView.as_view(), name='robot_details_view'),
    # path('fish_tanks/', views.FishTanksView.as_view(), name='fish_tanks_view'),
    # path('ros_interface/', views.ROSInterface.as_view(), name='ros_interface'),
    # path('ros_interface/<model>', views.ROSInterface.as_view(), name='ros_interface'),
]

gira/urls.py
from django.urls import path

from . import views

app_name = 'sugal'
urlpatterns = [
    path('', views.GiraListView.as_view(), name='gira_listview'),
    path('bike', views.add_log, name='gira_addlog'),
]

idmindserver/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('command_center.urls', namespace='command_center')),
    # path('command/', include('command_center.urls')),
    # re_path(r'^()|(command)/', include('command_center.urls', namespace='command_center')),
    path('loop/', include('loop.urls', namespace='loop')),
    path('sugal/', include('sugal.urls', namespace='sugal')),
    path('gira/', include('gira.urls', namespace='gira')),
]

loop/urls.py
from django.urls import path

from . import views

app_name = 'loop'
urlpatterns = [
    path('', views.LoopList.as_view(), name='overview'),
    path('<pk>/', views.LoopDetail.as_view(), name='loop_detail'),
    path('<pk>/logs', views.LoopLogList.as_view(), name='loop_log_list'),
    path('get_logs', views.get_logs, name="get_logs"),
    path('add_log', views.add_log, name="add_log"),
    path('get_stats', views.get_statistics, name="get_statistics"),
    # path('daily_stats', views.get_daily_statistics, name="get_daily_statistics"),
    path('week_stats', views.get_week_statistics, name="get_week_statistics"),
    # path('month_stats', views.get_month_statistics, name="get_month_statistics"),
]

loop/models.py
from django.db import models
from django.utils import timezone


class LoopLog(models.Model):
    timestamp = models.DateTimeField(verbose_name="Timestamp", default=timezone.now)
    node = models.CharField(max_length=50, verbose_name="Node", default="")
    data = models.CharField(max_length=500, verbose_name="Data", default="")

    def __str__(self):
        return "Time: {}\nNode: {}\nMessage: {}\n".\
            format(self.timestamp.strftime("%Y-%m-%d %H:%M"), self.node, self.data)

    class Meta:
            indexes = [
                models.Index(fields=['node', 'data'])
            ]

loop/views.py
from django.http import JsonResponse, HttpResponseServerError, HttpResponse, Http404, HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from command_center.models import RobotDetails, RobotLog
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta, date, time
from calendar import monthrange
from math import ceil
import json
import pytz

lx_tz = pytz.timezone("Portugal")


class LoopList(LoginRequiredMixin, ListView):
    """
    Class that returns the robots belonging to the Loop Project
    If there is only one robot, redirect to its detail view
    """
    login_url = '/accounts/login'
    model = RobotDetails
    queryset = RobotDetails.objects.filter(project__name="Loop")
    context_object_name = "loop_project_list"
    template_name = 'loop/loop.html'


class LoopDetail(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login'
    model = RobotDetails
    context_object_name = "loop_detail"
    template_name = 'loop/loop.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["loop_project_list"] = RobotDetails.objects.filter(project__name="Loop")
        return context


class LoopLogList(LoginRequiredMixin, ListView):
    login_url = '/accounts/login'
    model = RobotLog
    context_object_name = "loop_log_list"
    template_name = 'loop/loop.html'
    paginate_by = 30

    def get_queryset(self):

        # Apply time filters
        try:
            start_time = lx_tz.localize(datetime.strptime(self.request.GET["start"], "%Y-%m-%dT%H:%M"))
        except KeyError:
            start_time = lx_tz.localize(datetime.combine(date.today(), time()))
        try:
            stop_time = lx_tz.localize(datetime.strptime(self.request.GET["stop"], "%Y-%m-%dT%H:%M"))
        except KeyError:
            stop_time = lx_tz.localize(datetime.combine(date.today(), time.max))
        logs = RobotLog.objects.filter(robot__name="Loop", timestamp__range=(start_time, stop_time)).order_by('-timestamp')

        # Apply node filters
        try:
            nodes = []
            if len(self.request.build_absolute_uri().split('?')) > 1:
                params = self.request.build_absolute_uri().split('?')[1]
                for p in params.split('&'):
                    if p.split('=')[0] == 'nodes':
                        nodes.append((p.split('=')[1]).replace("%2F", "/"))
                # If no filter is applied, the request could only have page number
                if len(nodes) > 0:
                    logs = logs.filter(node__in=nodes)
        except KeyError:
            print("No nodes were specified")


        return logs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["loop_log_flag"] = True
        context["loop_project_list"] = RobotDetails.objects.filter(project__name="Loop")
        context["loop_nodes"] = RobotLog.objects.filter(robot__name="Loop").order_by('node').values('node').distinct()
        return context


@login_required
def get_logs(request):
    # lx_tz = pytz.timezone("Portugal")
    log_dict = {}
    print("Getting Logs")
    try:
        if request.method == "GET":
            robot = RobotDetails.objects.get(name=request.GET["robot"])

            unodes = request.GET["node"].split("|")

            ustart = lx_tz.localize(datetime.strptime(request.GET["start"], "%d-%m-%Y %H:%M"))
            ustop = lx_tz.localize(datetime.strptime(request.GET["stop"], "%d-%m-%Y %H:%M"))
            page = int(request.GET["page"])
            total_per_page = 25

            log_dict = {}
            print(robot)
            print(unodes)
            print(ustart)
            print(ustop)
            logs = RobotLog.objects.\
                filter(robot=robot, node__in=unodes, timestamp__range=(ustart, ustop)).\
                order_by('-timestamp')
            print(logs)
            page_logs = logs[(page-1)*total_per_page:page*total_per_page]

            for idx, lg in enumerate(page_logs):
                log_dict.update({str(idx): {"node": lg.node,
                                            "day": lg.timestamp.astimezone(lx_tz).date(),
                                            "time": lg.timestamp.astimezone(lx_tz).time(),
                                            "data": lg.data}})
            log_dict.update({"max_pages": ceil(len(logs)/total_per_page)})

    except Exception as err:
        print("Exception occurred: "+str(err))
        return HttpResponseServerError()
    else:
        return JsonResponse(log_dict)


# @login_required
# def get_daily_statistics(request):
#     log_dict = {}
#     try:
#         print("Getting Daily Statistics")
#         if request.method == "GET":
#             start_time = datetime.combine(date.today(), time(hour=0, minute=0, second=0), tzinfo=lx_tz)
#             stop_time = datetime.combine(date.today(), time(hour=23, minute=59, second=59), tzinfo=lx_tz)
#             print("{} | {}".format(start_time, stop_time))
#             log_dict["missions_started"] = RobotLog.objects.filter(robot__name="Loop",
#                                                                    timestamp__range=(start_time, stop_time),
#                                                                    data__contains="Mission started").count()
#             log_dict["missions_completed"] = RobotLog.objects.filter(robot__name="Loop",
#                                                                      timestamp__range=(start_time, stop_time),
#                                                                      data__contains="Mission completed").count()
#             mission_logs = RobotLog.objects.filter(robot__name='Loop',
#                                                    timestamp__range=(start_time, stop_time),
#                                                    data__regex="Mission|restarting").order_by('timestamp').count()
#             print("Logs: {}".format(mission_logs))
#
#
#
#
#             log_dict["reboots"] = RobotLog.objects.filter(robot__name="Loop",
#                                                           timestamp__range=(start_time, stop_time),
#                                                           data__contains="***** Logging is restarting *****").count()
#         else:
#             print("Method not allowed")
#             return HttpResponse(status=403)
#     except Exception as err:
#         print("Exception: {}".format(err))
#         return HttpResponseServerError(err)
#     return JsonResponse(log_dict)


@login_required
def get_statistics(request):
    """
        Returns a dictionary with three fields: 'day, 'week', 'month'
        Each field contains 'start, 'stop','started', 'completed','reboots'
    """
    log_dict = {'msg': 'Communication'}
    try:
        start = datetime.now()
        if request.method == "GET":
            day = int(request.GET["start_day"][0:2])
            month = int(request.GET["start_day"][2:4])
            year = int(request.GET["start_day"][4:])

            # Get monthly stats
            start_time = datetime.combine(date(year, month, 1), time(hour=0, minute=0, second=0), tzinfo=lx_tz)
            stop_time = datetime.combine(date(year, month, monthrange(year, month)[1]), time(hour=23, minute=59, second=59), tzinfo=lx_tz)
            month_mission_logs = RobotLog.objects.filter(robot__name='Loop',
                                                   timestamp__range=(start_time, stop_time),
                                                   data__regex=r'^(Mission [a-zA-Z]+)|(.+ restarting .+)$').order_by('timestamp')

            log_day = datetime.today()
            start_week = datetime(year, month, day, tzinfo=lx_tz)
            # Search stops at 00:00 of Monday
            stop_week = start_week + timedelta(days=7)
            day_dict = {"start": log_day, "started": 0, "completed": 0, "reboots": 0}
            week_dict = {"start": start_week, "stop": stop_week, "started": 0, "completed": 0, "reboots": 0}
            month_dict = {"start": start_time, "stop": stop_time, "started": 0, "completed": 0, "reboots": 0}

            last = ""
            for log in month_mission_logs:
                is_today = (log.timestamp.date() == log_day.date())
                is_week = (start_week.date() <= log.timestamp.date() <= stop_week.date())
                if ("started" in log.data) and not ("started" in last):
                    month_dict["started"] += 1
                    if is_week:
                        week_dict["started"] += 1
                    if is_today:
                        day_dict["started"] += 1
                elif ("completed" in log.data) and ("started" in last):
                    month_dict["completed"] += 1
                    if is_week:
                        week_dict["completed"] += 1
                    if is_today:
                        day_dict["completed"] += 1
                elif "restarting" in log.data:
                    month_dict["reboots"] += 1
                    if is_week:
                        week_dict["reboots"] += 1
                    if is_today:
                        day_dict["reboots"] += 1
                last = log.data

            log_dict = {'day': day_dict, 'week': week_dict, 'month': month_dict}
        else:
            print("Method not allowed")
            return HttpResponse(status=403)
        print("General statistics compiled in {}".format((datetime.now()-start).total_seconds()))
    except Exception as err:
        print("Exception: {}".format(err))
        return HttpResponseServerError(err)
    return JsonResponse(log_dict)


@login_required
def get_week_statistics(request):
    """

loop/templates/loop/loop.html
{% extends "base.html" %}

{% block app_imports %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/loop.css' %}" />
<link rel="stylesheet" href="{% static 'css/loop_statistics.css' %}" />
<script src="{% static 'js/moment.js' %}"></script>
<script src="{% static 'js/Chart.js' %}"></script>
<script src="{% static 'js/datetimepicker_css.js' %}"></script>
<script src="{% static 'js/easeljs.js' %}"></script>
<script src="{% static 'js/eventemitter2.js' %}"></script>
<script src="{% static 'js/roslib.js' %}"></script>
<script src="{% static 'js/ros2d.js' %}"></script>
<script src="{% static 'js/menus.js' %}"></script>
<script src="{% static 'js/loop.js' %}"></script>
<script src="{% static 'js/loop_ros.js' %}"></script>
<script src="{% static 'js/loop_statistics.js' %}"></script>
<!-- Added for datetime picker, due to use of static -->
<script>
    var imageFilesPath = "{% static 'img/' %}";
</script>
<meta name="viewport" content="width=device-width" />
{% endblock app_imports %}

{% block content %}
<div id="content">
    <p class="breadcrumbs"><a href="{% url 'command_center:project_list' %}">< Projects</a></p>
    <H1>Loop</H1>
    {% if system_messages %}
        <div style="flex: 0 1 100%" id="system_messages">
            <p>{{ system_messages }}</p>
        </div>
    {% endif %}
    <div id="robots_list_container">
        {% if loop_detail or loop_log_flag %}
            <p onclick="switch_display('robots_list')">Robots in Loop <img src="{% static 'img/cal_minus.gif' %}" ></p>
        {% else %}
            <p>Robots in Loop</p>
        {% endif %}
        <div id="robots_list" {% if loop_detail or loop_log_flag %} style="display:none" {% endif %}>
        {% if loop_project_list %}
                {% for r in loop_project_list %}
                    <div class="list-item">
                        <a href="{% url 'loop:loop_detail' r.name %}"><div class="item-container">
                            <img src="{% get_static_prefix %}img/robots/{{ r.name|lower }}.png" alt="{{ r.name }}" />
                            <div class="hover-text">
                                <a href="{% url 'loop:loop_detail' r.name %}" class="hover-text-a">{{ r.name }}</a>
                            </div>
                        </div></a>
                    </div>
                {% endfor %}
        {% else %}
            <p>There are no robots associated with this project.</p>
        {% endif %}
        </div>
    </div>
    <div id="loop_details">
    {% if loop_detail or loop_log_flag %}
        <div id="navbar">
            <a href="{% url 'loop:loop_detail' 'Loop' %}"><button class="tab_button" {% if loop_detail %}id="open"{% endif %}>Statistics</button></a>
            <a href="{% url 'loop:loop_log_list' 'Loop' %}"><button class="tab_button" {% if loop_log_flag %}id="open"{% endif %}>Logs</button></a>
        </div>
        {% if loop_log_flag %}
        <div class="tabcontent" id="logs">
            <div class="flex-title"><h3>Logs</h3></div>
            <div>
                <form>
                    {% csrf_token %}
                    <fieldset>
                        <legend>Filters</legend>
                        <div class="flex-row-wrapper">
                            <div class="multiselect">
                                <div class="selectBox" onclick="showCheckboxes()" style="width: 300px;">Select nodes<img src="{% static 'img/cal_minus.gif' %}" /></div>
                                <div id="checkboxes">
                                    {% for node in loop_nodes %}
                                        <div><input type="checkbox" name="nodes" value="{{ node.node }}" checked>{{ node.node }}</div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div>From: <input type="datetime-local" id="start_input" name="start" value="">
                            </div>
                            <div>To: <input type="datetime-local" id="stop_input" name="stop" value="">
                            </div>
                            <input type="submit">
                        </div>
                    </fieldset>
                </form>
                <script>
                    set_default_values();
                </script>
            </div>
            <div id="page_select" align="center">
                Page:
                {% if page_obj.has_previous %}<img class="page_nav" src="{% static 'img/cal_reverse.gif' %}" onclick="change_page({{ page_obj.previous_page_number }});">{% endif %}
                <span id="curr_page">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
                {% if page_obj.has_next %}<img class="page_nav" src="{% static 'img/cal_forward.gif' %}" onclick="change_page({{ page_obj.next_page_number }});">{% endif %}
            </div>
            <table id="log_table">
                <thead>
                    <tr>
                        <th style="width: 20%;">Node</th>
                        <th style="width: 15%;">Day</th>
                        <th style="width: 15%;">Time</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody>
                {% for l in loop_log_list %}
                    <tr>
                        <td>{{ l.node }}</td>
                        <td>{{ l.timestamp|date:"d M Y" }}</td>
                        <td>{{ l.timestamp|date:"G:i:s" }}</td>
                        <td>{{ l.data }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% elif loop_detail %}
            <div class="tabcontent" id="statistics">
                <div class="flex-title"><h3>Statistics</h3></div>
                <div id="missions_info_div">
                    <p id="daily_stats"></p>
                    <p id="week_stats"></p>
                    <p id="month_stats"></p>
                </div>
                <div id="missions_chart_div">
                    Ano: <select id="mission_year" onchange="list_weeks()"></select>
                    Semana: <select id="mission_week" onchange="display_plot()"></select>
                    <canvas id="missions_chart" width="200px" height="100px"></canvas>
                </div>
            </div>

        <script>
            list_years();
            list_weeks();
            display_plot();
        </script>
        {% endif %}
    {% endif %}
    </div>
</div>
{% endblock %}

loop/templates/loop/loop2.html
{% extends "base.html" %}

{% block app_imports %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/loop.css' %}" />
<link rel="stylesheet" href="{% static '/css/loop_statistics.css' %}" />
<script src="{% static '/js/moment.js' %}"></script>
<script src="{% static '/js/Chart.js' %}"></script>
<script src="{% static '/js/datetimepicker_css.js' %}"></script>
<script src="{% static '/js/easeljs.js' %}"></script>
<script src="{% static '/js/eventemitter2.js' %}"></script>
<script src="{% static '/js/roslib.js' %}"></script>
<script src="{% static '/js/ros2d.js' %}"></script>
<script src="{% static '/js/menus.js' %}"></script>
<script src="{% static '/js/loop.js' %}"></script>
<script src="{% static '/js/loop_ros.js' %}"></script>
<script src="{% static '/js/loop_statistics.js' %}"></script>
<!-- Added for datetime picker, due to use of static -->
<script>
    var imageFilesPath = "{% static 'img/' %}";
</script>
<meta name="viewport" content="width=device-width" />
{% endblock app_imports %}

{% block content %}
<div id="content">
    <p class="breadcrumbs"><a href="{% url 'command_center:project_list' %}">< Projects</a></p>
    <H1>Loop</H1>
    {% if system_messages %}
        <div style="flex: 0 1 100%" id="system_messages">
            <p>{{ system_messages }}</p>
        </div>
    {% endif %}
    <div id="robots_list_container">
        {% if loop_detail %}
            <p onclick="switch_display('robots_list')">Robots in Loop <img src="{% static 'img/cal_minus.gif' %}" ></p>
        {% else %}
            <p>Robots in Loop</p>
        {% endif %}
        <div id="robots_list" {% if loop_detail %} style="display:none" {% endif %}>
        {% if loop_list %}
                {% for r in loop_list %}
                    <div class="list-item">
                        <div class="item-container">
                            <img src="{% get_static_prefix %}img/robots/{{ r.name|lower }}.png" alt="{{ r.name }}" />
                            <div class="hover-text">
                                <a href="{% url 'loop:loop_detail' r.name %}" class="hover-text-a">{{ r.name }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        {% else %}
            <p>There are no robots associated with this project.</p>
        {% endif %}
        </div>
    </div>
    <div id="loop_details">
    {% if loop_detail %}
        <div id="navbar">
            <button class="tab_button" onclick="select_tab(event, 'statistics')">Statistics</button>
            <button class="tab_button" id="open" onclick="select_tab(event, 'logs')">Logs</button>
        </div>
        <div class="tabcontent" id="logs">
            <div class="flex-title"><h3>Logs</h3></div>
            <div>
                <form>
                    <fieldset>
                        <legend>Filters</legend>
                        <div class="flex-row-wrapper">
                            <div class="multiselect">
                                <div class="selectBox" onclick="showCheckboxes()" style="width: 200px;" >
                                <select>
                                    <option>Select nodes</option>
                                </select>
                                <div class="overSelect"></div>
                                </div>
                                <div id="checkboxes">
                                    {% for node in loop_nodes %}
                                        <label for="{{ node.node }}">
                                        <input type="checkbox" class="log_nodes" id="{{ node.node }}" onchange="update_table()" checked>{{ node.node }}
                                        </label>
                                    {% endfor %}
                                </div>
                            </div>
                            <div>From: <input id="log_start" type="text" maxlength="25" size="25" onchange="update_table()">
                                <img src="{% static 'img/cal.gif' %}" style="cursor: pointer"
                                     onclick="javascript:NewCssCal('log_start','ddMMYYYY','arrow',true,'24',false)" />
                            </div>
                            <div>To: <input id="log_end" type="text" maxlength="25" size="25" onchange="update_table()">
                                <img src="{% static 'img/cal.gif' %}" style="cursor: pointer"
                                     onclick="javascript:NewCssCal('log_end','ddMMYYYY','arrow',true,'24',false)" />
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div id="page_select" align="center">
                Page:
                <img class="page_nav" src="{% static 'img/cal_reverse.gif' %}" onclick="change_page(-1)" >
                <span id="curr_page">1 of 1</span>
                <img class="page_nav" src="{% static 'img/cal_forward.gif' %}" onclick="change_page(1)" >
            </div>

            <table id="log_table">
                <thead>
                    <tr>
                        <th style="width: 20%;">Node</th>
                        <th style="width: 15%;">Day</th>
                        <th style="width: 15%;">Time</th>
                        <th>Message</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        <div class="tabcontent" id="statistics" style="display: none">
            <div class="flex-title"><h3>Statistics</h3></div>
            <div id="missions_info_div">
                <p id="week_stats"></p>
                <p id="month_stats"></p>
            </div>
            <div id="missions_chart_div">
                Ano: <select id="mission_year" onchange="list_weeks()"></select>
                Semana: <select id="mission_week" onchange="display_plot()"></select>
                <canvas id="missions_chart" width="200px" height="100px"></canvas>
            </div>
        </div>
        <script>
            list_years();
            list_weeks();
            display_plot();
            update_table();
        </script>
    {% endif %}
    </div>
</div>
{% endblock %}

loop/templates/loop/loop_old.html
{% extends "idmind.html" %}

{% block app_imports %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/loop.css' %}" />
<link rel="stylesheet" href="{% static '/css/loop_statistics.css' %}" />
<script src="{% static '/js/datetimepicker_css.js' %}"></script>

<script src="{% static '/js/easeljs.js' %}"></script>
<script src="{% static '/js/eventemitter2.js' %}"></script>
<script src="{% static '/js/roslib.js' %}"></script>
<script src="{% static '/js/ros2d.js' %}"></script>
<script src="{% static '/js/loop.js' %}"></script>
<script src="{% static '/js/loop_ros.js' %}"></script>
<script src="{% static '/js/loop_statistics.js' %}"></script>
<!-- Added for datetime picker, due to use of static -->
<script>
    var imageFilesPath = "{% static 'images/' %}";
</script>
<meta name="viewport" content="width=device-width" />
{% endblock app_imports %}

{% block content %}
<H1>Loop</H1>
{% if system_messages %}
    <div style="flex: 0 1 100%" id="system_messages">
        <p>{{ system_messages }}</p>
    </div>
{% endif %}
<div id="navbar">
    <button class="tab_button" id="open" onclick="select_tab(event, 'logs')">Logs</button>
    <button class="tab_button" onclick="select_tab(event, 'statistics')">Statistics</button>
    <button class="tab_button" onclick="select_tab(event, 'current_state')">Current State</button>
</div>
<div class="tabcontent" id="logs">
    <div class="flex-title"><h3>Logs</h3></div>
    <div>
        <form>
            <fieldset>
                <legend>Filters</legend>
                <div class="flex-row-wrapper">
                    <div class="multiselect">
                        <div class="selectBox" onclick="showCheckboxes()" style="width: 200px;" >
                        <select>
                            <option>Select nodes</option>
                        </select>
                        <div class="overSelect"></div>
                        </div>
                        <div id="checkboxes">
                            {% for node in loop_nodes %}
                                <label for="{{ node.node }}">
                                <input type="checkbox" class="log_nodes" id="{{ node.node }}" onchange="update_table()" checked>{{ node.node }}
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                    <div>From: <input id="log_start" type="text" maxlength="25" size="25" onchange="update_table()">
                        <img src="{% static 'images/cal.gif' %}" style="cursor: pointer"
                             onclick="javascript:NewCssCal('log_start','ddMMYYYY','arrow',true,'24',false)" />
                    </div>
                    <div>To: <input id="log_end" type="text" maxlength="25" size="25" onchange="update_table()">
                        <img src="{% static 'images/cal.gif' %}" style="cursor: pointer"
                             onclick="javascript:NewCssCal('log_end','ddMMYYYY','arrow',true,'24',false)" />
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div id="page_select" align="center">
        Page:
        <img class="page_nav" src="{% static 'images/cal_reverse.gif' %}" onclick="change_page(-1)" >
        <span id="curr_page">1 of 1</span>
        <img class="page_nav" src="{% static 'images/cal_forward.gif' %}" onclick="change_page(1)" >
    </div>

    <table id="log_table">
        <thead>
            <tr>
                <th style="width: 20%;">Node</th>
                <th style="width: 15%;">Day</th>
                <th style="width: 15%;">Time</th>
                <th>Message</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div class="tabcontent" id="current_state">
    <div class="flex-title"><h3>State</h3></div>
    <div id="ros_msgs">
        <button id="connect_loop" onclick="connect_to_ros()">Connect to Loop</button>
    </div>
</div>
<div class="tabcontent" id="statistics">
    <div class="flex-title"><h3>Statistics</h3></div>
    <div id="missions_info_div">
        <p id="week_stats"></p>
        <p id="month_stats"></p>
    </div>
    <div id="missions_chart_div">
        Ano: <select id="mission_year" onchange="list_weeks()"></select>
        Semana: <select id="mission_week" onchange="display_plot()"></select>
        <canvas id="missions_chart" width="200px" height="100px"></canvas>
    </div>
</div>
<script>
    list_years();
    list_weeks();
    display_plot();
</script>

{% endblock %}