command_center/urls.py
from django.urls import path

from . import views

app_name = 'command_center'
urlpatterns = [
    path('', views.MainMenu.as_view(), name='main_menu'),
    path('command/', views.MainMenu.as_view(), name='main_menu'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/<pk>', views.ProjectDetailView.as_view(), name='project_detail'),    # This is called for projects that do not have their own app
    path('robot_list/', views.RobotListView.as_view(), name='robot_list'),
    # path('robot_list/<model>', views.RobotListView.as_view(), name='robot_list_view'),
    # # path('robot_details/<pk>', views.RobotDetailsView.as_view(), name='robot_details_view'),
    # path('robot_details/<pk>', views.RobotDetailsView.as_view(), name='robot_details_view'),
    # path('fish_tanks/', views.FishTanksView.as_view(), name='fish_tanks_view'),
    # path('ros_interface/', views.ROSInterface.as_view(), name='ros_interface'),
    # path('ros_interface/<model>', views.ROSInterface.as_view(), name='ros_interface'),
]

gira/urls.py
from django.urls import path

from . import views

app_name = 'sugal'
urlpatterns = [
    path('', views.GiraListView.as_view(), name='gira_listview'),
    path('bike', views.add_log, name='gira_addlog'),
]

idmindserver/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('command_center.urls', namespace='command_center')),
    # path('command/', include('command_center.urls')),
    # re_path(r'^()|(command)/', include('command_center.urls', namespace='command_center')),
    path('loop/', include('loop.urls', namespace='loop')),
    path('sugal/', include('sugal.urls', namespace='sugal')),
    path('gira/', include('gira.urls', namespace='gira')),
]

command_center/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Projects(models.Model):
    name = models.CharField(max_length=50, unique=True)
    project_start = models.DateTimeField('Start', default=timezone.now)
    active = models.BooleanField(default=True, verbose_name="Active Project")
    status = models.CharField(max_length=100,
                              choices=(("D", "Development"), ("De", "Deployment"), ("M", "Maintenance")), default="D")
    app_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_start(self):
        return self.project_start.strftime("%d %b %Y, %H:%M:%S")

    def get_status(self):
        return self.get_status_display()

    def is_active(self):
        return self.active

    class Meta:
        ordering = ('active', 'project_start',)
        verbose_name_plural = 'Projects'


class RobotModels(models.Model):
    name = models.CharField(max_length=100, verbose_name='Robot Model', default="Fishy", primary_key=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Robot Models'


class RobotDetails(models.Model):
    name = models.CharField(max_length=100, verbose_name='Robot Name', primary_key=True)
    model = models.ForeignKey(RobotModels, on_delete=models.CASCADE)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE, blank=True, default="")
    ip = models.GenericIPAddressField(verbose_name='IP Address', default="127.0.0.1")

    def __str__(self):
        return "{} robot, with IP {}".format(self.name, self.ip)

    class Meta:
        ordering = ('model', 'name',)
        verbose_name_plural = 'Robot Details'


class RobotLog(models.Model):
    robot = models.ForeignKey(RobotDetails, on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(verbose_name="Timestamp", default=timezone.now)
    node = models.CharField(max_length=50, verbose_name="Node", default="")
    data = models.CharField(max_length=500, verbose_name="Data", default="")

    def __str__(self):
        return "Time: {}\nNode: {}\nMessage: {}\n".\
            format(self.timestamp.strftime("%Y-%m-%d %H:%M"), self.node, self.data)

    class Meta:
        ordering = ('robot', 'timestamp',)
        verbose_name_plural = 'Robot Logs'

command_center/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Projects, RobotModels, RobotDetails
from django.contrib.auth.mixins import LoginRequiredMixin


# Consider using a different kind of view, that does not require context
class MainMenu(LoginRequiredMixin, ListView):
    login_url = '/accounts/login'
    model = Projects
    template_name = 'command_center/command_center.html'
    context_object_name = 'projects'


class ProjectListView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login'
    model = Projects
    template_name = 'command_center/project_list.html'
    context_object_name = 'projects'


class ProjectDetailView(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login'
    model = Projects
    template_name = 'command_center/project_list.html'
    context_object_name = 'projects'


class RobotListView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login'
    model = RobotDetails
    template_name = 'command_center/robot_list.html'
    context_object_name = 'robots'

    def get_context_data(self, **kwargs):
        # Adds information to the context
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['models'] = RobotModels.objects.all()
        return context

command_center/templates/command_center/command_center.html
{% extends "base.html" %}
{% load static %}
{% block app_imports %}
    <link rel="stylesheet" media="screen and (min-width: 600px)" href="{% static 'css/screen/command.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 600px)" href="{% static 'css/smallscreen/command.css' %}">
{% endblock %}
{% block title %}Command Center{% endblock %}

{% block content %}
<div id="content">
    <div id="main_menu">
        <div class="main_menu_item">
            <a href="{% url 'command_center:project_list' %}"><div class="item_container">
                <img src="{% get_static_prefix %}img/projects.png" alt="Projects" />
                <div class="hover-text">
                    <a href="{% url 'command_center:project_list' %}" class="hover-text-a">Projects</a>
                </div>
            </div></a>
        </div>
        <div class="main_menu_item">
            <a href="{% url 'command_center:robot_list' %}" class="hover-text-a"><div class="item_container">
                <img src="{% get_static_prefix %}img/robots.png" alt="Robots" />
                <div class="hover-text">
                    <a href="{% url 'command_center:robot_list' %}" class="hover-text-a">Robots</a>
                </div>
            </div></a>
        </div>
    </div>
</div>
{% endblock %}

command_center/templates/command_center/command_center2.html
{% extends "base.html" %}
{% load static %}
{% block app_imports %}
    <link rel="stylesheet" media="screen and (min-width: 600px)" href="{% static 'css/screen/command.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 600px)" href="{% static 'css/smallscreen/command.css' %}">
{% endblock %}
{% block title %}Command Center{% endblock %}

{% block content %}
<h1>Command Center</h1>
<div id="content">
    <div id="projects_list">
        {% if projects %}
            {% for p in projects %}
                <div class="list-item">
                    <div class="item-container">
                        <img src="{% get_static_prefix %}img/projects/{{ p|lower }}.png" alt="{{ p }}" />
                        <div class="hover-text">
                            <a href="{{ p.app_name }}/"><p class="hover-text-p">{{ p }}</p></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no projects to display</p>
        {% endif %}
    </div>
    <div id="models_list">
        {% if models %}
            {% for m in models %}
                <div class="list-item">
                    <div class="item-container">
                        <img src="{% get_static_prefix %}img/models/{{ m|lower }}.png" alt="{{ m }}" />
                        <div class="hover-text">
                            <p class="hover-text-p">{{ m }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no robot models to display</p>
        {% endif %}
    </div>
</div>
{% endblock %}

command_center/templates/command_center/project_list.html
{% extends "base.html" %}
{% load static %}
{% block app_imports %}
    <link rel="stylesheet" media="screen and (min-width: 600px)" href="{% static 'css/screen/projects.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 600px)" href="{% static 'css/smallscreen/projects.css' %}">
{% endblock %}
{% block title %}Command Center - Projects{% endblock %}

{% block content %}
<div id="content">
    <div id="projects_list">
        {% if projects %}
            {% for p in projects %}
                <div class="list-item">
                    <a href="/{{ p.app_name }}/"><div class="item-container">
                        <img src="{% get_static_prefix %}img/projects/{{ p|lower }}.png" alt="{{ p }}" />
                        <div class="hover-text">
                            <a href="/{{ p.app_name }}/" class="hover-text-a">{{ p }}</a>
                        </div>
                    </div></a>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no projects to display</p>
        {% endif %}
    </div>
</div>
{% endblock %}

command_center/templates/command_center/robot_list.html
{% extends "base.html" %}
{% load static %}
{% block app_imports %}
    <link rel="stylesheet" media="screen and (min-width: 600px)" href="{% static 'css/screen/projects.css' %}">
    <link rel="stylesheet" media="screen and (max-width: 600px)" href="{% static 'css/smallscreen/projects.css' %}">
{% endblock %}
{% block title %}Command Center - Projects{% endblock %}

{% block content %}
<div id="content">
    <div id="robot_list">
        STILL UNDER WORK - Divide by models
        {% if robots %}
            {% for r in robots %}
                <div class="list-item">
                    <div class="item-container">
                        <img src="{% get_static_prefix %}img/robots/{{ r|lower }}.png" alt="{{ r }}" />
                        <div class="hover-text">
                            <a href="" class="hover-text-a">{{ r }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no robots to display</p>
        {% endif %}
    </div>
</div>
{% endblock %}