command_center/urls.py
from django.urls import path

from . import views

app_name = 'command_center'
urlpatterns = [
    path('', views.MainMenu.as_view(), name='main_menu'),
    path('command/', views.MainMenu.as_view(), name='main_menu'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/<pk>', views.ProjectDetailView.as_view(), name='project_detail'),    # This is called for projects that do not have their own app
    path('robot_list/', views.RobotListView.as_view(), name='robot_list'),
    # path('robot_list/<model>', views.RobotListView.as_view(), name='robot_list_view'),
    # # path('robot_details/<pk>', views.RobotDetailsView.as_view(), name='robot_details_view'),
    # path('robot_details/<pk>', views.RobotDetailsView.as_view(), name='robot_details_view'),
    # path('fish_tanks/', views.FishTanksView.as_view(), name='fish_tanks_view'),
    # path('ros_interface/', views.ROSInterface.as_view(), name='ros_interface'),
    # path('ros_interface/<model>', views.ROSInterface.as_view(), name='ros_interface'),
]

gira/urls.py
from django.urls import path

from . import views

app_name = 'sugal'
urlpatterns = [
    path('', views.GiraListView.as_view(), name='gira_listview'),
    path('bike', views.add_log, name='gira_addlog'),
]

idmindserver/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('command_center.urls', namespace='command_center')),
    # path('command/', include('command_center.urls')),
    # re_path(r'^()|(command)/', include('command_center.urls', namespace='command_center')),
    path('loop/', include('loop.urls', namespace='loop')),
    path('sugal/', include('sugal.urls', namespace='sugal')),
    path('gira/', include('gira.urls', namespace='gira')),
]

sugal/urls.py
from django.urls import path

from . import views

app_name = 'sugal'
urlpatterns = [
    path('', views.GPSListView.as_view(), name='sugal_listview'),                          # This shows the table of GPS, ordered by box_nr ##NEEDS TO BE CHANGED
    path('detail/<pk>', views.GPSDetailView.as_view(), name='sugal_detailview'),
    path('get_gps_list', views.get_gps_list, name='sugal_gpslist'),
    path('update_warnings/', views.update_warnings, name='sugal_warnings'),             # This should be called periodically to update warning messages
    path('detail/<imei>/get_bat_logs', views.get_gps_bat_logs, name="sugal_getbatlogs"),                   # Returns the logs of a given GPS (to update battery plots)
    path('detail/<imei>/get_gps_logs', views.get_gps_logs, name="sugal_getgpslogs"),                   # Returns the logs of a given GPS (to update battery plots)
    path('detail/<imei>/full_logs', views.GPSLogList.as_view(), name="sugal_fulllogs"),                   # Returns the logs of a given GPS (to update battery plots)
    # path('create_gps/',views.GPSCreate.as_view(), name="sugal_create_gps"),             # Returns the view to create a new GPS
    path('edit_gps/<int:pk>', views.GPSUpdate.as_view(), name="sugal_edit_gps"),         # Returns the view to edit a GPS
    path('add_log/', views.add_log, name='sugal_addlog'),                               # Function that adds a log to the database
    path('add_multiple_log/', views.add_multiple_log, name='sugal_addmultilog'),                               # Function that adds multiple logs to the database
]

sugal/forms.py
from django import forms
from django.core.validators import RegexValidator

sugal/views.py
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from datetime import datetime, date, time, timedelta
from .models import GPSDevices, GPSLogs
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import json
import pytz
import re

valid = {"V": "Valid", "I": "Invalid", "H": "Heartbeat", "S": "Sleep", "A": "Awake"}
lx_tz = pytz.timezone("Portugal")


class GPSListView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login'
    model = GPSDevices
    template_name = "sugal/gps_list.html"
    context_object_name = "gps_devices"
    paginate_by = 20

    def get_ordering(self):
        print(self.kwargs)
        if not self.kwargs:
            ordering = 'imei'
        else:
            ordering = self.kwargs['pk']
        return ordering


class GPSDetailView(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login'
    model = GPSDevices
    context_object_name = "gps_detail"
    template_name = 'sugal/gps_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gps_list'] = GPSDevices.objects.order_by('box_nr', 'imei')
        return context


class GPSLogList(LoginRequiredMixin, ListView):
    login_url = '/accounts/login'
    model = GPSLogs
    template_name = 'sugal/gps_logs.html'
    context_object_name = "gps_logs"
    paginate_by = 20

    def get_queryset(self):

        # Apply time filters
        try:
            start_time = lx_tz.localize(datetime.strptime(self.request.GET["start"], "%Y-%m-%dT%H:%M"))
        except KeyError:
            start_time = lx_tz.localize(datetime.combine(date.today(), time()))
        try:
            stop_time = lx_tz.localize(datetime.strptime(self.request.GET["stop"], "%Y-%m-%dT%H:%M"))
        except KeyError:
            stop_time = lx_tz.localize(datetime.combine(date.today(), time.max))
        logs = GPSLogs.objects.filter(gps__imei=self.kwargs['imei'], timestamp_received__range=(start_time, stop_time)).order_by('timestamp_received')

        # Apply event filter
        try:
            ev = self.request.GET["log_event"]
            if ev.isnumeric():
                logs = logs.filter(event=int(ev))
        except KeyError:
            print("No event was specified")

        # Apply validity filter
        try:
            valid = self.request.GET["log_valid"]
            if valid != 'all':
                logs = logs.filter(valid=valid)
        except KeyError:
            print("No validity label was specified")

        return logs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gps_detail'] = GPSDevices.objects.get(imei=self.kwargs['imei'])
        context['gps_events'] = GPSLogs.objects.order_by().values('event').distinct()
        context['gps_valid'] = GPSLogs.objects.order_by().values('valid').distinct()
        return context


class GPSCreate(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login'
    model = GPSDevices
    template_name = 'sugal/gps_form.html'


class GPSUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/accounts/login'
    model = GPSDevices
    template_name = 'sugal/gps_form.html'


@login_required
def get_gps_list(request):
    order = request.GET['order_by']
    gps_list = GPSDevices.objects.all().order_by(order)
    try:
        box = request.GET['box_nr']
        gps_list = gps_list.filter(box_nr__icontains=box)
    except KeyError:
        print("There are no box_nr filters")
    try:
        imei = request.GET['imei']
        gps_list = gps_list.filter(imei__icontains=imei)
    except KeyError:
        print("There are no imei filters")
    try:
        charging = (request.GET['charging'] == 'true')
        gps_list = gps_list.filter(charging=charging)
    except KeyError:
        print("There are no charging filters")
    try:
        server = request.GET['server']
        gps_list = gps_list.filter(server=server)
    except KeyError:
        print("There are no server filters")

    gps_dict = {}
    for g in gps_list:
        gps_dict.update({str(g): {
            "model": g.model,
            "box_nr": g.box_nr,
            "imei": g.imei,
            "serial_number": g.serial_number,
            "owner": g.owner,
            "server": g.server,
            "phone_number": g.phone_number,
            "license_plate": g.license_plate,
            "state": g.state,
            "charging": g.charging,
            "warning": g.warning,
        }})
    return JsonResponse(gps_dict)


@login_required
def get_gps_bat_logs(request, imei):
    """
    Returns the gps logs of a given GPS as JSON (for displaying in chart)
    :param request:
    :param imei:
    :return:
    """
    response = {}
    if request.method == "GET":
        # imei = request.GET["imei"]
        day = lx_tz.localize(datetime.strptime(request.GET["day"], "%d-%m-%Y"))
        startday = day.replace(hour=0, minute=0, second=0)
        endday = day.replace(hour=23, minute=59, second=59)
        logs = GPSLogs.objects.filter(gps__imei=imei, timestamp_msg__range=(startday, endday)).order_by('timestamp_msg')
        for idx, lg in enumerate(logs):
            response[str(idx)] = (lg.timestamp_msg.astimezone(lx_tz), lg.battery, lg.ext_battery)
        return JsonResponse(response)
    else:
        return JsonResponse(response)


@login_required
def get_gps_logs(request, imei):
    """
    Returns the gps logs of a given GPS as JSON (for displaying in chart)
    :param request:
    :param imei:
    :return:
    """
    response = {}
    if request.method == "GET":
        # order = request.GET.get('order', 'timestamp_msg')
        order = request.GET.get('order_by')
        qtd = int(request.GET.get('limit'))
        logs = GPSLogs.objects.filter(gps__imei=imei).order_by(order)[0:qtd]
        for idx, lg in enumerate(logs):
            response.update({str(idx): {
                "timestamp_received": lg.timestamp_received,
                "timestamp_msg": lg.timestamp_msg,
                "latitude": lg.latitude,
                "longitude": lg.longitude,
                "event": lg.event,
                "speed": lg.speed,
                "valid": lg.valid,
                "battery": lg.battery,
                "ext_battery": lg.ext_battery,
                "raw": lg.raw,
            }})
        return JsonResponse(response)
    else:
        return JsonResponse(response)


@csrf_exempt
def add_log(request):
    print("Received a new log "),
    if request.method == "POST":
        try:
            data = json.loads(request.body.decode("utf-8", "strict"))
            try:
                gps_imei = data["id"]
                gps_model = "M"
                gps_dev = GPSDevices.objects.get(imei=gps_imei, model=gps_model)
            except ObjectDoesNotExist:
                gps_dev = GPSDevices()
                gps_dev.imei = data["id"]
                gps_dev.model = "M"
                if data["server"] == "pt":
                    gps_dev.server = "PROD PT"
                elif data["server"] == "es":
                    gps_dev.server = "PROD ES"
                elif data["server"] == "qa":
                    gps_dev.server = "QA"
                else:
                    gps_dev.server = data["server"]
                gps_dev.warning = 1
                gps_dev.comments = "Created automatically"
                gps_dev.save()
                print("New GPS created")
            print(gps_dev)
            try:
                try:
                    # Check if log already exists
                    raw_msg = msg_parser(data["message_raw"])
                    ts = pytz.timezone("Europe/Lisbon").localize(
                        datetime.strptime(str(raw_msg["timestamp"]), "%y%m%d%H%M%S"))
                    tr = pytz.timezone("Europe/Lisbon").localize(
                        datetime.strptime(str(data["timestamp"]), "%y%m%d%H%M%S"))
                    gps_log = GPSLogs.objects.get(gps=gps_dev, timestamp_msg=ts, timestamp_received=tr)
                    print("Log already exists")
                    return HttpResponse(status=409)
                except MultipleObjectsReturned:
                    print("Log already exists... twice...")
                    return HttpResponse(status=409)
                except ObjectDoesNotExist:
                    print("Saving log...")
                    gps_log = GPSLogs()
                    gps_log.gps = gps_dev
                    ts = pytz.timezone("Europe/Lisbon").localize(
                        datetime.strptime(str(raw_msg["timestamp"]), "%y%m%d%H%M%S"))
                    gps_log.timestamp_msg = ts
                    if "timestamp_received" in data.keys():
                        ts = pytz.timezone("Europe/Lisbon").localize(
                            datetime.strptime(str(data["timestamp_received"]), "%y%m%d%H%M%S"))
                    else:
                        ts = pytz.timezone("Europe/Lisbon").localize(datetime.now())
                    gps_log.timestamp_received = ts
                    gps_log.latitude = data["latitude"]
                    gps_log.longitude = data["longitude"]
                    gps_log.event = raw_msg["event"]
                    gps_log.speed = data["velocity"]
                    gps_log.valid = data["valid"]
                    gps_log.battery = data["battery"]
                    gps_log.ext_battery = data["ext_battery"] if data["ext_battery"] != 655.35 else -1
                    gps_log.raw = data["message_raw"]
                    gps_log.save()
                    gps_dev.charging = True if float(gps_log.ext_battery) > 3. else False
                    gps_dev.save()
                    print("Log saved")

sugal/templates/sugal/gps_detail.html
{% extends "base.html" %}

{% block app_imports %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/sugal.css' %}" />
<link rel="stylesheet" href="{% static 'css/gps_modal.css' %}" />
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}" />
<script src="{% static 'js/sugal.js' %}"></script>
<script src="{% static 'js/gps_modal.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
<script src="{% static 'js/moment.js' %}"></script>
<script src="{% static 'js/Chart.js' %}"></script>
{% endblock app_imports %}

{% block content %}
<div id="content">
    <p class="breadcrumbs"><a href="{% url 'sugal:sugal_listview' %}">< GPS List</a></p>
    <H1>SUGAL</H1>
    {% if system_messages %}
        <div style="flex: 0 1 100%" id="system_messages">
            <p>{{ system_messages }}</p>
        </div>
    {% endif %}
    <div id="device_detail">
    {% if gps_detail %}
        <div id="gps_selection">
<!--            <form method="GET" action="choose_gps">-->
    <!--        <p>Choose GPS: <select id="detail_imei" oninput="request_plot_data(new Date())">-->
                <p>Choose GPS: <select name="gps_id" id="detail_imei" onchange="window.location.href='/sugal/detail/'+this.value">
                {% for dev in gps_list %}
                    <option {% ifequal dev.imei gps_detail.imei %} selected="selected" {% endifequal %} value="{{ dev.imei }}">Box: {{ dev.box_nr }} - {{ dev.imei }}</option>
                {% endfor %}
                </select>
<!--                <input type="submit" value="Go">-->
                </p>
<!--            </form>-->
        </div>
        <div id="info_div">
            <table width="100%">
            {% for name, value in gps_detail.as_dict %}
                <tr><td style='font-weight:bold'>{{ name }}</td><td align="right">{{ value }}</td></tr>
            {% endfor %}
            </table>
            <p align="center"><a href="{% url 'sugal:sugal_edit_gps' gps_detail.imei %}"><button>Edit <img src="{% static 'img/edit.png' %}" height="15px"/></button></a></p>
        </div>
        <div id="gps_chart">
            <div><label for="log_calendar">Choose Day</label><input type="date" id="log_calendar" oninput="update_plot_data()"/></div>
            <canvas id="gpslog_chart" width="200px" height="100px"></canvas>
        </div>
        <div id="loglist">
            <table id="log_list_table">
                <thead>
                    <tr>
                        <td>Received</td>
                        <td>Generated</td>
                        <td>Lat.</td>
                        <td>Long.</td>
                        <td>Event</td>
                        <td>Speed</td>
                        <td>Valid</td>
                        <td>Battery</td>
                        <td>Ext. Battery</td>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tfoot>
                    <tr><td colspan="9"><a href="{% url 'sugal:sugal_fulllogs' gps_detail.imei %}"><button>Full logs</button></a></td></tr>
                </tfoot>
            </table>
        </div>
        <script>
            today = new Date();
            document.getElementById("log_calendar").value = convert_date(today, 'ymd');
            document.getElementById("log_calendar").max = convert_date(today, 'ymd');
            request_plot_data(today);
            request_gps_logs('-timestamp_received', 10);
        </script>

    {% else %}
        <p>No GPS devices are available.</p>
    {% endif %}
    </div>

</div>
{% endblock %}

sugal/templates/sugal/gps_form.html
{% extends "base.html" %}

{% block app_imports %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/sugal.css' %}" />
<link rel="stylesheet" href="{% static 'css/gps_modal.css' %}" />
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}" />
<script src="{% static 'js/sugal.js' %}"></script>
<script src="{% static 'js/gps_modal.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock app_imports %}

{% block content %}
<div id="content">
    <p class="breadcrumbs"><a href="{% url 'command_center:project_list' %}">< Projects</a></p>
    <H1>SUGAL - FORM UNDER WORK</H1>
    {% if system_messages %}
        <div style="flex: 0 1 100%" id="system_messages">
            <p>{{ system_messages }}</p>
        </div>
    {% endif %}
    {% if gps_devices %}
        <table id="device_list_table">
            <thead>
            <tr>
                <th>Box</th>
                <th>IMEI</th>
                <th>Server</th>
                <th>Charging</th>
                <th>Warnings</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for g in gps_devices %}
                <tr>
                    <td>{{ g.box_nr }}</td>
                    <td>{{ g.imei }}</td>
                    <td>{{ g.server }}</td>
                    <td>{{ g.charging }}</td>
                    <td>
                        {% if g.warning == 0 %}<a href="{% url 'sugal:sugal_detailview' g.imei %}"><img src="{% static 'img/green_light.jpg' %}" height="15px" /></a>
                        {% elif g.warning == 1 %}<a href="{% url 'sugal:sugal_detailview' g.imei %}"><img src="{% static 'img/yellow_light.jpg' %}" height="15px" /></a>
                        {% elif g.warning == 2 %}<a href="{% url 'sugal:sugal_detailview' g.imei %}"><img src="{% static 'img/red_light.jpg' %}" height="15px" /></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no GPS devices in the database. Add GPS</p>
    {% endif %}
</div>
{% endblock %}

sugal/templates/sugal/sugal.html
{% extends "base.html" %}

{% block app_imports %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/sugal.css' %}" />
<link rel="stylesheet" href="{% static '/css/gps_modal.css' %}" />
<link rel="stylesheet" href="{% static '/css/datepicker.css' %}" />
<script src="{% static 'js/sugal.js' %}"></script>
<script src="{% static 'js/gps_modal.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
<meta name="viewport" content="width=device-width" />
{% endblock app_imports %}

{% block content %}
<div id="content">
    <H1>SUGAL</H1>
    {% if system_messages %}
        <div style="flex: 0 1 100%" id="system_messages">
            <p>{{ system_messages }}</p>
        </div>
    {% endif %}
    <div id="navbar">
        <!--<button class="tab_button" {% if gps_table %} id="open" {% endif %} onclick="location.href=/sugal/' %}">Device List</button>-->
        <button class="tab_button" {% if gps_devices or new_gps or edit_gps %} id="open" {% endif %} onclick="location.href='{% url 'sugal:sugal_listview' %}'">Device List</button>
        <button class="tab_button" {% if gps_detail %} id="open" {% endif %} onclick="location.href='{% url 'sugal:sugal_detailview' %}'">Device Detail</button>
        <button class="tab_button" {% if gps_log %} id="open" {% endif %} onclick="location.href='{% url 'sugal:sugal_logview' %}'">Logs</button>
    </div>

    {% if gps_devices or new_gps or edit_gps %}
    <div class="tabcontent" id="device_list">
        {% if new_gps %}
        <h3> Add New GPS</h3>
        <table>
            <form method="post">{% csrf_token %}
                {{ form.as_table }}
                <tr><td colspan="2"><input type="submit" value="Save"></td></tr>
            </form>
        </table>
        {% elif edit_gps %}
        <h3> Edit GPS</h3>
        <table>
            <form method="post">{% csrf_token %}
                {{ form.as_table }}
                <tr><td colspan="2"><input type="submit" value="Save"></td></tr>
            </form>
        </table>
        {% elif gps_devices %}
        <div>
            <p><a href="{% url 'sugal_create_gps' %}"><button>Add GPS</button></a></p>
            0<table id="device_list_table">
                <thead>
                    <tr>
                        <th><a href="{% url 'sugal:sugal_listview_order' 'state_asc' %}"><img src="{% static 'img/arrow_up.png' %}" height="15px" /></a>State<a href="{% url 'sugal:sugal_listview_order' 'state_dsc' %}"><img src="{% static 'img/arrow_down.png' %}" height="15px" /></a></th>
                        <th><a href="{% url 'sugal:sugal_listview_order' 'box_nr_asc' %}"><img src="{% static 'img/arrow_up.png' %}" height="15px" /></a>Box<a href="{% url 'sugal:sugal_listview_order' 'box_nr_dsc' %}"><img src="{% static 'img/arrow_down.png' %}" height="15px" /></a></th>
                        <th>IMEI</th>
                        <th>Server</th>
                        <th>Phone Nr.</th>
                        <th>License</th>
                        <th><a href="{% url 'sugal:sugal_listview_order' 'warning_asc' %}"><img src="{% static 'img/arrow_up.png' %}" height="15px" /></a>Warnings<a href="{% url 'sugal:sugal_listview_order' 'warning_dsc' %}"><img src="{% static 'img/arrow_down.png' %}" height="15px" /></a></th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dev in gps_devices %}
                    <tr>
                        <td>{{ dev.state }}</td>
                        <td>{{ dev.box_nr }}</td>
                        <td>{{ dev.imei }}</td>
                        <td>{{ dev.server }}</td>
                        <td>{{ dev.phone_number }}</td>
                        <td>{{ dev.license_plate }}</td>
                        <td>
                            {% if dev.warning == 0 %}<a href="{% url 'sugal:sugal_detailview' dev.imei %}"><img src="{% static 'img/green_light.jpg' %}" height="15px" /></a>
                            {% elif dev.warning == 1 %}<a href="{% url 'sugal:sugal_detailview' dev.imei %}"><img src="{% static 'img/yellow_light.jpg' %}" height="15px" /></a>
                            {% elif dev.warning == 2 %}<a href="{% url 'sugal:sugal_detailview' dev.imei %}"><img src="{% static 'img/red_light.jpg' %}" height="15px" /></a>
                            {% endif %}
                        </td>
                        <td><a href="{% url 'sugal:sugal_edit_gps' dev.imei %}"><img src="{% static 'img/edit.png' %}" height="15px"/></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div><p>No GPS devices are available.</p></div>
        {% endif %}
    </div>
    {% elif gps_detail %}
    <div class="tabcontent" id="device_detail">
        {% if gps_detail %}
        <div id="gps_selection">
            <form method="GET" action="choose_gps">
    <!--        <p>Choose GPS: <select id="detail_imei" oninput="request_plot_data(new Date())">-->
                <p>Choose GPS: <select name="gps_id" id="detail_imei" >
                {% for dev in gps_list %}
                    <option {% ifequal dev.imei gps_detail.imei %} selected="selected" {% endifequal %} value="{{ dev.imei }}">Box: {{ dev.box_nr }} - {{ dev.imei }}</option>
                {% endfor %}
                </select>
                <input type="submit" value="Go">
                </p>
            </form>
        </div>
        <div id="info_div">
            <table width="100%">
            {% for name, value in gps_detail.as_dict %}
                <tr><td style='font-weight:bold'>{{ name }}</td><td align="right">{{ value }}</td></tr>
            {% endfor %}
            </table>
            <p align="center"><a href="{% url 'sugal:sugal_edit_gps' gps_detail.imei %}"><button>Edit <img src="{% static 'img/edit.png' %}" height="15px"/></button></a></p>
        </div>
        <div id="gps_chart">
            <div><label for="log_calendar">Choose Day</label><input type="date" id="log_calendar" oninput="update_plot_data()"/></div>
            <canvas id="gpslog_chart" width="200px" height="100px"></canvas>
        </div>
        <script>
            today = new Date();
            document.getElementById("log_calendar").value = convert_date(today, 'ymd');
            document.getElementById("log_calendar").max = convert_date(today, 'ymd');
            request_plot_data(today);
        </script>

        {% else %}
        <p>No GPS devices are available.</p>
        {% endif %}

    </div>
    {% elif gps_log_view %}
    <div class="tabcontent" id="log_history">
        <div style="margin: 10px">
    <!--        <label for="log_list_calendar">Choose Day</label><input type="date" id="log_list_calendar" oninput="location.href='{% url 'sugal:sugal_logview' gps.imei 1 %}'"/>-->
    <!--        <p>Choose GPS: <select id="detail_imei" oninput="request_plot_data(new Date())">-->
            <form method="GET" action="">
                <label for="log_list_calendar">Choose Day</label><input type="date" name="log_date" id="log_list_calendar" value="2019-07-05" >
                <p>Choose GPS: <select name="gps_id" id="detail_imei_log" >
                {% for dev in gps_list %}
                    <option {% ifequal dev.imei gps.imei %} selected="selected" {% endifequal %} value="{{ dev.imei }}" >Box: {{ dev.box_nr }} - {{ dev.imei }}</option>
                {% endfor %}
                </select>
                <input type="submit" value="Go">
                </p>
            </form>
        </div>
        <div id="log_list">
            {% if gps_log %}
                <table id="loglist_table">
                    <thead>
                        <tr>
                            <th>GPS</th>
                            <th>Timestamp</th>
                            <th>Validity</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                            <th>Speed</th>
                            <th>Int. Battery</th>
                            <th>Ext. Battery</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for log in gps_log %}
                            <tr>
                                <td>{{ log.gps }}</td>
                                <td>{{ log.timestamp }}</td>
                                <td>{{ log.valid }}</td>
                                <td>{{ log.latitude }}</td>
                                <td>{{ log.longitude }}</td>
                                <td>{{ log.speed }}</td>
                                <td>{{ log.battery }}</td>
                                <td>{{ log.ext_battery }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                {% if last_log %}
                    <p>There are no logs to display for this day. Last log was on {{ last_log.timestamp }} </p>
                {% else %}
                    <p> There are no logs from this device</p>
                {% endif %}
            {% endif %}
        </div>
        <script>
            vars = location.search.substr(1).split("&").reduce((o,i)=>(u=decodeURIComponent,[k,v]=i.split("="),o[u(k)]=v&&u(v),o),{});
            if(vars.log_date){
                dt = new Date(vars.log_date);
            }
            else{
                dt = new Date();
            }
            document.getElementById("log_list_calendar").value = convert_date(dt, 'ymd');
            document.getElementById("log_list_calendar").max = convert_date(new Date(), 'ymd');
        </script>
    </div>
    {% else %}
    <p>There are no GPS in the database. <a href="{% url 'sugal:sugal_create_gps' %}">Add GPS</a></p>
    {% endif %}
</div>
{% endblock %}